name: Daily Design News

on:
  schedule:
    - cron: '0 23 * * *'     # 毎日 08:00 JST
  workflow_dispatch:         # 手動実行ボタン
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 履歴ファイルの更新に必要
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory /home/runner/work/newsbot/newsbot
          git config --global credential.helper store
          echo "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Initialize news history
        run: |
          set -e
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la
          
          if [ ! -f news_history.json ]; then
            echo "Creating new news history file"
            echo '{"items":[]}' > news_history.json
            git add -f news_history.json
            git commit -m "Initialize news history file"
            git push origin main
          else
            echo "News history file exists"
            cat news_history.json
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run news delivery
        run: npm start
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          FEEDS: ${{ secrets.FEEDS }}

      - name: Commit and push if changed
        run: |
          set -e
          echo "Checking for changes in news history"
          git add -f news_history.json
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected in news history"
            git status
            git diff news_history.json
            git commit -m "Update news history"
            git pull --rebase origin main
            git push origin main
          fi 