name: Daily News Delivery

on:
  schedule:
    - cron: '0 23 * * *'  # 毎日23:00 UTC (08:00 JST)
  workflow_dispatch:  # 手動実行用

jobs:
  deliver:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Run news delivery
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          FEEDS: ${{ secrets.FEEDS }}
          LIMIT: ${{ secrets.LIMIT }}
        run: npm start 